name: Upload Code to GCS

on:
  push:
    branches: [main]

permissions:
  id-token: write      # ✅ Required for Workload Identity Federation
  contents: read       # ✅ Required for actions/checkout

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/17096885802/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@clever-coast-461101-t5.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload code to GCS bucket
        run: |
          gsutil cp src/word_count.py gs://cvs-qa/scripts/
